import type { Applicant } from '@/types/applicant'

export const mockApplicants: Applicant[] = [
  {
    id: '1',
    firstName: 'Aisha',
    lastName: 'Patel',
    nuid: '001234567',
    email: 'patel.ai@northeastern.edu',
    major: 'Computer Science',
    year: 3,
    stage: 'application',
    submittedAt: '2026-06-01',
  },
  {
    id: '2',
    firstName: 'Marcus',
    lastName: 'Chen',
    nuid: '001345678',
    email: 'chen.ma@northeastern.edu',
    major: 'Information Systems',
    year: 2,
    stage: 'interview',
    rating: 'good_hire',
    submittedAt: '2026-05-28',
  },
  {
    id: '3',
    firstName: 'Sofia',
    lastName: 'Nguyen',
    nuid: '001456789',
    email: 'nguyen.so@northeastern.edu',
    major: 'Computer Science',
    year: 4,
    stage: 'offered',
    rating: 'must_hire',
    submittedAt: '2026-05-20',
  },
  {
    id: '4',
    firstName: 'Jordan',
    lastName: 'Williams',
    nuid: '001567890',
    email: 'williams.jo@northeastern.edu',
    major: 'Data Science',
    year: 3,
    stage: 'rejected',
    rating: 'no_hire',
    submittedAt: '2026-05-15',
  },
  {
    id: '5',
    firstName: 'Priya',
    lastName: 'Sharma',
    nuid: '001678901',
    email: 'sharma.pr@northeastern.edu',
    major: 'Computer Science',
    year: 1,
    stage: 'application',
    submittedAt: '2026-06-03',
  },
  {
    id: '6',
    firstName: 'Liam',
    lastName: "O'Brien",
    nuid: '001789012',
    email: 'obrien.li@northeastern.edu',
    major: 'Cybersecurity',
    year: 2,
    stage: 'interview',
    rating: 'great_hire',
    submittedAt: '2026-05-30',
  },
  {
    id: '7',
    firstName: 'Zoe',
    lastName: 'Kim',
    nuid: '001890123',
    email: 'kim.zo@northeastern.edu',
    major: 'Information Systems',
    year: 3,
    stage: 'offered',
    rating: 'great_hire',
    submittedAt: '2026-05-18',
  },
  {
    id: '8',
    firstName: 'Ethan',
    lastName: 'Rivera',
    nuid: '001901234',
    email: 'rivera.et@northeastern.edu',
    major: 'Computer Science',
    year: 5,
    stage: 'application',
    submittedAt: '2026-06-05',
  },
  {
    id: '9',
    firstName: 'Nadia',
    lastName: 'Hassan',
    nuid: '002012345',
    email: 'hassan.na@northeastern.edu',
    major: 'Data Science',
    year: 4,
    stage: 'rejected',
    rating: 'no_hire',
    submittedAt: '2026-05-12',
  },
  {
    id: '10',
    firstName: 'Tyler',
    lastName: 'Brooks',
    nuid: '002123456',
    email: 'brooks.ty@northeastern.edu',
    major: 'Computer Science',
    year: 3,
    stage: 'interview',
    rating: 'must_hire',
    submittedAt: '2026-06-02',
  },
]
